name: firstworkflow

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest

        steps:
          - name: sample hello-world display
            run: echo hello-world

          - name: checkout option
            uses: actions/checkout@v2

          - name: print env variables
            run: env | sort


    job2:
        name: Second Job
        runs-on: ubuntu-latest

        steps:
          - name: second job first task
            run: env | sort
          - name: second job print echo msg
            run: echo hello-maddy




